<h1><?php echo $this->translate('Add a new product'); ?></h1>

<?php
//\Zend\Debug\Debug::dump($this->registerForm);
?>
<?php echo $this->form()->openTag($this->productForm) ?>
    <dl class="zend_form">
    <?php foreach ($this->productForm->getFieldsets()['product']->getElements() as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php if (!$element instanceof Zend\Form\Element\Hidden): ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>


