<h1><?php echo $this->translate('Edit user'); ?></h1>

<?php if ($this->messages): ?>
    <?php foreach ($this->messages as $message): ?>
        <h2><?php echo $message ?></h2>
    <?php endforeach ?>
<?php endif ?>
<?php echo $this->form()->openTag($this->userProfileForm) ?>
    <dl class="zend_form">
    <?php foreach ($this->userProfileForm->getFieldsets()['profile']->getElements() as $element): ?>
        <?php if ($element->getName() == 'profile[u_id]'): ?>
            <?php $element->setValue($loggedUser->getId()) ?>
        <?php endif ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php if (!$element instanceof Zend\Form\Element\Hidden and $element->getAttribute('type') != 'hidden'): ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <dd><?php echo $this->formButton($element) ?></dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
        <?php else: ?>
            <dd><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
        <?php endif ?>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>


