<h1>Current User Information</h1>
Email: <?php echo $this->identity->getUEmail(); ?> <br />
Mobile: <?php echo $this->identity->getUMobilePhone(); ?> <br />

<a href='sp/add'>发布产品销售信息</a>

<form action='search/buyer' method='post'>
	<input type='text' name='name' />
	<input type='submit' value='Search buyers' />
</form>

<form action='search/seller' method='post'>
	<input type='text' name='name' />
	<input type='submit' value='Search sellers' />
</form>

<table>
	<?php foreach ($this->users as $user): ?>
		<tr>
			<td> <?php echo $user->getUEmail(); ?> </td>
			<td> <?php echo $user->getUType(); ?></td>
			<td> <?php echo $user->getUProducts(); ?></td>
		</tr>
	<?php endforeach ?>
</table>
