<h1>Welcome <?php echo $this->identity->getUEmail(); ?></h1>

<a href='sp/add'>发布产品销售信息</a>

<form action='search/buyer' method='post'>
	<input type='text' name='name' />
	<input type='submit' value='Search buyer' />
</form>

<form action='search/seller' method='post'>
	<input type='text' name='name' />
	<input type='submit' value='Search seller' />
</form>

<table>
	<?php foreach ($this->users as $user): ?>
		<tr>
			<td> <?php echo $user->getUEmail(); ?> </td>
			<td> <?php echo $user->getUType(); ?></td>
			<td> <?php echo $user->getUProducts(); ?></td>
		</tr>
	<?php endforeach ?>
</table>
