<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('%s测试我们的小手网站 %s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">这里是行业分类</h3>
            </div>
            <div class "panel-body">
                <ul><!--下面数据应该来自于服务器 -->
                    <li class="xs_prod_type">矿山机械</li>
                    <li class="xs_prod_type">电力设备</li>
                    <li class="xs_prod_type">生产设备</li>
                    <li class="xs_prod_type">维修设备</li>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">这里是留给大图宣传</h3>
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">这里是推荐企业和推荐业务员信息,或者企业,业务员排行</h3>
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>
</div>
